apiVersion: v1
kind: Service
metadata:
  name: cutline
  namespace: cutline
  labels:
    app.kubernetes.io/name: cutline
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cutline
  ports:
    - name: http
      port: 80
      targetPort: http
