#!/usr/bin/env bash
# Build gitignored .env for local dev from Cutline-PROD (1Password).
# Default: local SQLite + prod R2/STT. Pass --prod-db to use Turso instead.
set -euo pipefail

USE_PROD_DB=false
for arg in "$@"; do
	case "$arg" in
		--prod-db) USE_PROD_DB=true ;;
		-h | --help)
			echo "Usage: $0 [--prod-db]"
			echo "  --prod-db  Use prod Turso (DATABASE_URL + DATABASE_AUTH_TOKEN from 1Password)"
			exit 0
			;;
		*) echo "Unknown option: $arg" >&2; exit 1 ;;
	esac
done

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/.env"
PROD_DOTENV="$(op read 'op://homelab7/Cutline-PROD/dotenv')"

if [[ "$USE_PROD_DB" == true ]]; then
	DB_NOTE='prod Turso DB'
	SKIP_KEYS='ORIGIN'
else
	DB_NOTE='local SQLite (file:local.db)'
	SKIP_KEYS='DATABASE_URL|DATABASE_AUTH_TOKEN|ORIGIN'
fi

{
	echo '# Local dev — generated by scripts/local-env.sh (not committed).'
	echo "# DB: $DB_NOTE; R2 + ASSEMBLYAI from Cutline-PROD via 1Password."
	echo '# Re-run: bash scripts/local-env.sh [--prod-db]'
	echo ''
	if [[ "$USE_PROD_DB" == false ]]; then
		echo 'DATABASE_URL=file:local.db'
	fi
	echo 'ORIGIN=http://localhost:5173'
	while IFS= read -r line || [[ -n "$line" ]]; do
		[[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
		key="${line%%=*}"
		if [[ "$USE_PROD_DB" == true ]]; then
			[[ "$key" == ORIGIN ]] && continue
		else
			case "$key" in
				DATABASE_URL | DATABASE_AUTH_TOKEN | ORIGIN) continue ;;
			esac
		fi
		printf '%s\n' "$line"
	done <<<"$PROD_DOTENV"
} >"$OUT"

chmod 600 "$OUT"
echo "Wrote $OUT ($DB_NOTE, prod bucket secrets)"
